changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Documentation changes
      labels:
        - documentation
        - tests
    - title: Other changes
      labels:
        - refactor
        - tooling
