name: Documentation

on:
  push:
    branches:
      - main
      - docusaurus

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Graaf repository
        uses: actions/checkout@v3

      - name: Install node
        run: sudo apt-get install nodejs npm -y

      - name: Install yarn
        run: npm install --global yarn

      - name: Build docs and deploy
        run: cd docs && yarn && yarn deploy