# This workflow warns issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 9 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        days-before-close: -1
        stale-issue-message: |
          Marking this issue as stale. It will **not** be automatically closed.

          Even though the maintainers of Graaf may not always have time to take a look in a timely fashion, your contributions are much appreciated.
          Please allow some time for @bobluppes to take a closer look.
        stale-pr-message: |
          Marking this PR as stale. It will **not** be automatically closed.

          Even though the maintainers of Graaf may not always have time to take a look in a timely fashion, your contributions are much appreciated.
          Please allow some time for @bobluppes to take a closer look.
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-pr-labels: 'dependencies'
